services:
  front:
    build: 
      context: ./front-spa
      dockerfile: dockerfile.front
    container_name: front-spa
    ports:
      - "4200:4200"
    volumes:
      - ./front-spa:/app
      - /app/node_modules
    depends_on:
      - back
  back:
    container_name: mock-api
    build: 
      context: ./mock-api
      dockerfile: dockerfile.api
    ports:
      - "3000:3000"
    volumes:
      - ./mock-api:/app

