version: '3.8'

services:
  frontend:
    build:
      context: ./front-spa
      dockerfile: Dockerfile.front
    container_name: angular-front
    ports:
      - "4200:4200"
    volumes:
      - ./front-spa:/app
      - /app/node_modules
    command: npm run start
    depends_on:
      - mockapi

  mockapi:
    image: clue/json-server
    container_name: mock-api
    ports:
      - "3000:80"
    volumes:
      - ./mock-api/db.json:/data/db.json
